### ISSUE TITLE
翻译关联 image 样式问题

### ISSUE THREAD

**Issue by sAMs126** [wordway/extension#25]
翻译结果对应的图片显式区域的样式是 `overflow: scroll;`

```css
.translate-result-view .images {
    margin-top: 12px;
    width: 325px;
    height: 82px;
    display: flex;
    overflow: scroll;
}
```

在 windows + chrome 环境下，显式背景框由于滚动条的存在显式错乱

![图片显式问题](https://s3.ax1x.com/2021/03/15/6BDXKf.png)

建议调整样式为 `overflow: auto;`

```diff
.translate-result-view .images {
    margin-top: 12px;
    width: 325px;
    height: 82px;
    display: flex;
-   overflow: scroll;
+   overflow: auto;
}
```

效果如下：

![修改图片显式效果](https://s3.ax1x.com/2021/03/15/6BDLxP.png)
